import { createDefaultModule, DefaultModuleContext, inject, LangiumServices, Module, PartialLangiumServices } from 'langium';
import { SimpleUiGeneratedModule } from './generated/module';
import { SimpleUiValidationRegistry, SimpleUiValidator } from './simple-ui-validator';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type SimpleUiAddedServices = {
    validation: {
        SimpleUiValidator: SimpleUiValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SimpleUiServices = LangiumServices & SimpleUiAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const SimpleUiModule: Module<SimpleUiServices, PartialLangiumServices & SimpleUiAddedServices> = {
    validation: {
        ValidationRegistry: (injector) => new SimpleUiValidationRegistry(injector),
        SimpleUiValidator: () => new SimpleUiValidator()
    }
};

/**
 * Inject the full set of language services by merging three modules:
 *  - Langium default services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 */
export function createSimpleUiServices(context?: DefaultModuleContext): SimpleUiServices {
    return inject(
        createDefaultModule(context),
        SimpleUiGeneratedModule,
        SimpleUiModule
    );
}
